baseURL = "https://www.codelust.dev/"
languageCode = "en-GB"
title = "CodeLust"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  # whether to use inline CSS instead of an external CSS file for syntax highlighting
  # required for Chroma (https://github.com/alecthomas/chroma) to work with Hugo
  noClasses = false

[params]
  # the name of the content directory (default is "content/posts")
  # the list of created content will show up on the index page (baseurl)
  contentTypeName = "posts"

  # the maximum number of items to display on the navigation bar
  # items that exceed this count will display in a "Show More" menu
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if the resources directory contains an image called "cover.(jpg|png|webp)" then the file will be used as a cover automatically
  # to have a resources directory, create a folder with the name of the content page, move the markdown file inside, and rename the markdown file to index.md
  # the "cover" property can be removed from the content page markdown while this parameter is set to "true"
  autoCover = true

  # allow Hugo to access Git information that can be used for content page metadata (https://gohugo.io/methods/page/gitinfo/)
  # the last modification date for each content page will be the date of the last commit for that file
  enableGitInfo = true

  # whether or not to display when content pages were last updated
  showLastUpdated = true

  # provide a string as a prefix for the last update date
  # by default, it looks like the following: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # whether to show a content page's estimated reading time
  readingTime = true

  # whether or not to show a table of contents on content pages
  # can be overridden in a content page's front-matter
  toc = false

  # the title for the table of contents
  # can be overridden in a content page's front-matter
  tocTitle = "Table Of Contents"

  # Set date/time format for content pages
  # This will impact the date/time displayed on
  # index.html, the list of content pages, and on content pages themselves
  # This value can also be configured per content page on front-matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Terminal"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showcase"
          name = "Showcase"
          url = "/showcase"
		  
		[[languages.en.menu.main]]
          identifier = "abou1t"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "show2case"
          name = "Showcase"
          url = "/showcase"
		          [[languages.en.menu.main]]
          identifier = "ab3out"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "show4case"
          name = "Showcase"
          url = "/showcase"
		  
		[[languages.en.menu.main]]
          identifier = "ab1out"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showc3ase"
          name = "Showcase"
          url = "/showcase"
		  		[[languages.en.menu.main]]
          identifier = "ab2out"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showc3ase"
          name = "Showcase"
          url = "/showcase"
		          [[languages.en.menu.main]]
          identifier = "ab4out"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showc5ase"
          name = "Showcase"
          url = "/showcase"
		  
		[[languages.en.menu.main]]
          identifier = "abo2ut"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showc5a6se"
          name = "Showcase"
          url = "/showcase"
		          [[languages.en.menu.main]]
          identifier = "showc3ase"
          name = "Showcase"
          url = "/showcase"
		          [[languages.en.menu.main]]
          identifier = "ab43out"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "sh6owc5ase"
          name = "Showcase"
          url = "/showcase"
		  
		[[languages.en.menu.main]]
          identifier = "ab4o2ut"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "sho6wc5ase"
          name = "Showcase"
          url = "/showcase"

[caches]
  [caches.assets]
    dir = ':cacheDir/assets'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1
