baseURL = "https://www.codelust.dev/"
languageCode = "en-GB"
title = "CodeLust"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  # whether to use inline CSS instead of an external CSS file for syntax highlighting
  # required for Chroma (https://github.com/alecthomas/chroma) to work with Hugo
  noClasses = false

[params]
  # the name of the content directory (default is "content/posts")
  # the list of created content will show up on the index page (baseurl)
  contentTypeName = "posts"

  # the maximum number of items to display on the navigation bar
  # items that exceed this count will display in a "Show More" menu
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if the resources directory contains an image called "cover.(jpg|png|webp)" then the file will be used as a cover automatically
  # to have a resources directory, create a folder with the name of the content page, move the markdown file inside, and rename the markdown file to index.md
  # the "cover" property can be removed from the content page markdown while this parameter is set to "true"
  autoCover = true

  # allow Hugo to access Git information that can be used for content page metadata (https://gohugo.io/methods/page/gitinfo/)
  # the last modification date for each content page will be the date of the last commit for that file
  enableGitInfo = true

  # whether or not to display when content pages were last updated
  showLastUpdated = true

  # provide a string as a prefix for the last update date
  # by default, it looks like the following: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # whether to show a content page's estimated reading time
  readingTime = true

  # whether or not to show a table of contents on content pages
  # can be overridden in a content page's front-matter
  toc = false

  # the title for the table of contents
  # can be overridden in a content page's front-matter
  tocTitle = "Table Of Contents"

  # the date/time format (https://gohugo.io/functions/time/format/)
  # applies to the index page, the list of content pages, and on content pages themselves
  # can be overridden in a content page's front-matter
  dateFormat = "2006-01-02 15:04"

[frontmatter]
  date = [":git", "date"]
  lastmod = [":git", "lastmod"]

[languages]
  [languages.en]
    languageName = "English"
    title = "CodeLust"

    [languages.en.params]
      subtitle = "Binary Hedonism"
      owner = "Aleksander Reinhardt"
      keywords = "codelust, binary, hedonism"
      copyright = "© 2025 Aleksander Reinhardt"
      menuMore = "Show More"
      readMore = "Read More"
      readOtherPosts = "Read Other Posts"
      newerPosts = "Newer Posts"
      olderPosts = "Older Posts"
      missingContentMessage = "Page Not Found ..."
      missingBackButtonLabel = "Back To Index"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "CodeLust"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "about"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "featured"
          name = "featured"
          url = "/featured"

[caches]
  [caches.assets]
    dir = ':cacheDir/assets'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1
